#!/bin/bash
set -e

# ==========================================
# OpenCV.js Build Script with LSD Support
# Tested on Ubuntu 20.04
# ==========================================

WORK_DIR="opencv_js_build"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

echo "[1/6] Installing system dependencies..."
sudo apt-get update -y || true
sudo apt-get install -y git cmake python3 python3-pip npm default-jre

echo "[2/6] Setting up Emscripten (SDK)..."
if [ ! -d "emsdk" ]; then
    git clone https://github.com/emscripten-core/emsdk.git
fi
cd emsdk
# Pin to 3.1.25 which works with Python 3.8 and OpenCV 4.x
./emsdk install 3.1.25
./emsdk activate 3.1.25
source ./emsdk_env.sh
cd ..

echo "[3/6] Cloning OpenCV Source..."
if [ ! -d "opencv" ]; then
    git clone --depth 1 -b 4.x https://github.com/opencv/opencv.git
fi

echo "[4/6] Cleaning cached configurations..."
# Delete cached whitelist.json that might be stale
rm -f opencv/build_wasm/modules/js_bindings_generator/whitelist.json
rm -rf opencv/build_wasm
echo "Removed cached build artifacts."

echo "[5/6] Patching Configuration for LineSegmentDetector..."
CONFIG_FILE="opencv/platforms/js/opencv_js.config.py"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Config file not found at $CONFIG_FILE"
    exit 1
fi

# First, remove any old patches we may have added
if grep -q "PATCH ADDED BY BUILD SCRIPT" "$CONFIG_FILE"; then
    echo "Removing old patch from config file..."
    # Remove everything from the patch marker to end of file
    sed -i '/# ===================================================$/,$ d' "$CONFIG_FILE"
fi

# Check if LineSegmentDetector class is already properly defined in imgproc dict
if grep -q "'LineSegmentDetector':" "$CONFIG_FILE"; then
    echo "LineSegmentDetector class already exists in imgproc dictionary."
else
    echo "Adding LineSegmentDetector class to imgproc dictionary..."
    
    # Insert LineSegmentDetector class right before the CLAHE line
    # The CLAHE line looks like:     'CLAHE': ['apply', ...
    python3 << 'PATCH_SCRIPT'
import re

config_file = "opencv/platforms/js/opencv_js.config.py"

with open(config_file, 'r') as f:
    content = f.read()

# Check if already patched
if "'LineSegmentDetector':" in content:
    print("Already patched!")
else:
    # Insert LineSegmentDetector definition before CLAHE
    # Pattern matches the CLAHE line with proper indentation
    new_content = content.replace(
        "    'CLAHE': [",
        "    'LineSegmentDetector': ['detect', 'drawSegments', 'compareSegments'],\n    'CLAHE': ["
    )
    
    if new_content != content:
        with open(config_file, 'w') as f:
            f.write(new_content)
        print("✓ Successfully added LineSegmentDetector class to imgproc dictionary!")
    else:
        print("✗ Failed to find CLAHE pattern. Manual patching may be needed.")
        exit(1)
PATCH_SCRIPT
fi

# Verify the patch
echo "Verifying patch..."
if grep -q "'LineSegmentDetector':" "$CONFIG_FILE"; then
    echo "✓ Patch verified successfully!"
    echo "--- imgproc section showing LineSegmentDetector ---"
    grep -B2 -A2 "'LineSegmentDetector'" "$CONFIG_FILE"
    echo "--- End of imgproc section ---"
else
    echo "✗ Patch verification failed!"
    exit 1
fi

# Also verify that the config file can be properly parsed by Python
echo "Verifying config file syntax..."
python3 -c "
# Define makeWhiteList function (from embindgen.py)
def makeWhiteList(module_list):
    wl = {}
    for m in module_list:
        for k in m.keys():
            if k in wl:
                wl[k] += m[k]
            else:
                wl[k] = m[k]
    return wl

with open('$CONFIG_FILE') as f:
    exec(f.read())

print('white_list keys:', list(white_list.keys())[:20])
if 'LineSegmentDetector' in white_list:
    print('✓ LineSegmentDetector IS in white_list with methods:', white_list['LineSegmentDetector'])
else:
    print('✗ LineSegmentDetector NOT in white_list!')
    print('Available keys:', sorted(white_list.keys()))
"

echo "[6/6] Building OpenCV.js..."
cd opencv
source ../emsdk/emsdk_env.sh

# Build with clean build directory
# CRITICAL: --config forces use of our patched config file instead of autogenerated whitelist.json
python3 platforms/js/build_js.py build_wasm \
    --build_wasm \
    --simd \
    --clean_build_dir \
    --config platforms/js/opencv_js.config.py

echo "=========================================="
echo "Build Complete!"
echo "Your artifacts are located in: $(pwd)/build_wasm/bin"
echo "files: opencv.js"
echo "=========================================="
echo ""
echo "To verify, check the built file for LineSegmentDetector:"
echo "  grep -o 'LineSegmentDetector' build_wasm/bin/opencv.js | head -5"
